### ISSUE TITLE
TypeError: sequence item 0: expected str instance, NoneType found

### ISSUE THREAD

**Issue by jeromerobert** [jeromerobert/pdfarranger#153]
Adding [this](https://github.com/jeromerobert/pdfarranger/files/4301666/683053.pdf) file then saving trigger the following error:
```
$ /mingw64/bin/python3 -m pdfarranger
Traceback (most recent call last):
  File "C:\msys64\home\jerome\pdfarranger/pdfarranger/pdfarranger.py", line 641, in choose_export_pdf_name
    self.save(only_selected, file_out)
  File "C:\msys64\home\jerome\pdfarranger/pdfarranger/pdfarranger.py", line 195, in wrapper
    func(*args, **kwargs)
  File "C:\msys64\home\jerome\pdfarranger/pdfarranger/pdfarranger.py", line 686, in save
    m = metadata.merge(self.metadata, self.pdfqueue)
  File "C:\msys64\home\jerome\pdfarranger/pdfarranger/metadata.py", line 66, in merge
    r[k] = v
  File "C:/Users/jerome/.local/lib/python3.8/site-packages/pikepdf/models/metadata.py", line 389, in __exit__
    self._apply_changes()
  File "C:/Users/jerome/.local/lib/python3.8/site-packages/pikepdf/models/metadata.py", line 454, in _apply_changes
    self._update_docinfo()
  File "C:/Users/jerome/.local/lib/python3.8/site-packages/pikepdf/models/metadata.py", line 410, in _update_docinfo
    value = converter.docinfo_from_xmp(value)
  File "C:/Users/jerome/.local/lib/python3.8/site-packages/pikepdf/models/metadata.py", line 172, in docinfo_from_xmp
    return '; '.join(xmp_val)
TypeError: sequence item 0: expected str instance, NoneType found
```
Reproduced with pikepdf 1.9.0 and 1.10.2. The bug is in pikepdf but can be easily avoided on pdfarranger side. More details coming soon.

**Comment by jeromerobert** [comment]
https://github.com/pikepdf/pikepdf/issues/84
