### ISSUE TITLE
Command "python setup.py egg_info" failed

### ISSUE THREAD

**Issue by stavpup** [jeromerobert/pdfarranger#50]
Install fails with this message;

` pip3 install --user -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt

Collecting https://github.com/jeromerobert/pdfarranger/zipball/master (from -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt (line 1))
  Downloading https://github.com/jeromerobert/pdfarranger/zipball/master
     | 686kB 7.3MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-b70g4cf6/setup.py", line 27, in <module>
        from DistUtilsExtra.command import *
    ModuleNotFoundError: No module named 'DistUtilsExtra'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-b70g4cf6/
`

**Comment by jeromerobert** [comment]
You are missing [python-distutils-extra](https://launchpad.net/python-distutils-extra). You should find it in your package manager. Would you tell us what is your Linux distribution (or other system) and how you install `python-distutils-extra` (and other dependences) so I could update the installation instruction ?

**Comment by stavpup** [comment]
You are correct. Here is the new command
`sudo pacman -S poppler-glib python-distutils-extra python-pip python-gobject gtk3 python-cairo python-distutils-extra`

Manjaro linux
