### ISSUE TITLE
Cannot save with certain PDFs

### ISSUE THREAD

**Issue by jcrows** [jeromerobert/pdfarranger#85]
Saving is not possible when cropping certain PDFs. After typing a new file name and hitting save, it brings up the error shown. The same error was occurring on Arch linux and on the Windows version. However, when I printed the PDF to another PDF file it saved without any trouble. 

![bug](https://user-images.githubusercontent.com/1057735/59641001-037a5380-91b4-11e9-81f7-ac1ec152f2f4.png)

[Sample PDF for reproducing the bug](https://github.com/jeromerobert/pdfarranger/files/3299077/Anchor.Bible.Dictionary.-.Covenant.-.Selected.Pages.pdf)

**Comment by jeromerobert** [comment]
This is https://github.com/mstamy2/PyPDF2/issues/337

**Comment by acheronfail** [comment]
I'm still seeing this issue:

```Traceback (most recent call last):
  File "/home/cosmotherly/.local/lib/python3.7/site-packages/pdfarranger/pdfarranger.py", line 593, in choose_export_pdf_name
    self.save(only_selected, file_out)
  File "/home/cosmotherly/.local/lib/python3.7/site-packages/pdfarranger/pdfarranger.py", line 196, in wrapper
    func(*args, **kwargs)
  File "/home/cosmotherly/.local/lib/python3.7/site-packages/pdfarranger/pdfarranger.py", line 634, in save
    exporter.export(self.pdfqueue, to_export, file_out)
  File "/home/cosmotherly/.local/lib/python3.7/site-packages/pdfarranger/exporter.py", line 98, in _pypdf2
    current_page.rotateClockwise(angle)
  File "/usr/lib/python3/dist-packages/PyPDF2/pdf.py", line 2150, in rotateClockwise
    self._rotate(angle)
  File "/usr/lib/python3/dist-packages/PyPDF2/pdf.py", line 2166, in _rotate
    self[NameObject("/Rotate")] = NumberObject(currentAngle + angle)
TypeError: unsupported operand type(s) for +: 'IndirectObject' and 'int'```

Running Ubuntu 19.04, and using version `1.3.0` of `pdfarranger`

**Comment by jeromerobert** [comment]
@acheronfail Same symptom but a the bug is a bit different. Could you provide a PDF file to reproduce it ? (and ideally open a new bug report).

As a quick workaround you can `apt install python3-pikepdf`
