### ISSUE TITLE
ValueError: Pointer arguments are restricted to integers, capsules, and None

### ISSUE THREAD

**Issue by stolzpet** [jeromerobert/pdfarranger#88]
Hi Jerome,

I compiled pdfarranger (openSUSE Tumbleweed) with:
./setup.py build
running build
running build_py
running build_i18n
intltool-update -p -g pdfarranger
running build_icons

Then i start it:
python3 -m pdfarranger
Traceback (most recent call last):
  File "/home/stolz/Downloads/pdfarranger-1.2.1/pdfarranger/pdfarranger.py", line 289, in do_activate
    self.uiXML.connect_signals(self)
ValueError: Pointer arguments are restricted to integers, capsules, and None. See: https://bugzilla.gnome.org/show_bug.cgi?id=683599

Why this error? What can I do?

Greetings Peter

**Comment by stolzpet** [comment]
Same error with:
pip3 install --user -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt
Collecting https://github.com/jeromerobert/pdfarranger/zipball/master (from -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt (line 1))
  Downloading https://github.com/jeromerobert/pdfarranger/zipball/master
     | 153kB 342kB/s
Requirement already satisfied: PyPDF2 in /usr/lib/python3.7/site-packages (from -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt (line 2)) (1.26.0)
Building wheels for collected packages: pdfarranger
  Building wheel for pdfarranger (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-f06_a7ml/wheels/f5/4d/26/7d838573abbbdd06c0bc865d5b7475d08fd2e08c074aeb9e1f
Successfully built pdfarranger
Installing collected packages: pdfarranger
  WARNING: The script pdfarranger is installed in '/home/stolz/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

 ./pdfarranger 
Traceback (most recent call last):
  File "/home/stolz/.local/lib/python3.7/site-packages/pdfarranger/pdfarranger.py", line 303, in do_activate
    self.uiXML.connect_signals(self)
ValueError: Pointer arguments are restricted to integers, capsules, and None. See: https://bugzilla.gnome.org/show_bug.cgi?id=683599

Peter

**Comment by jeromerobert** [comment]
> Why this error? What can I do?

I have no idea why you get this error. May be this is the same as https://github.com/kozec/sc-controller/issues/273 (also python GTK and OpenSUSE Tumbleweed). May be you could try to install the `python-gobject-common-devel` if you do not have it already.

**Comment by stolzpet** [comment]
Now it works!

Thanks a lot

Greetings Peter

**Comment by dreua** [comment]
Sounds like a packaging error to me, -devel packages should not be needed at runtime. It would be nice if you could report this against the python-gobject package in openSUSE @stolzpet .

For the record, I have the following python-gobject packages on my Fedora 31:
```
python3-gobject.x86_64                      3.34.0-3.fc31                @fedora
python3-gobject-base.x86_64                 3.34.0-3.fc31                @fedora
```

Containing those files:
```
[da@David-UB ~]$ rpm -ql python3-gobject
/usr/lib/.build-id
/usr/lib/.build-id/1e
/usr/lib/.build-id/1e/0069b4c149b951f05d0a5cc7e422c776fb3e41
/usr/lib64/python3.7/site-packages/gi/_gi_cairo.cpython-37m-x86_64-linux-gnu.so
[da@David-UB ~]$ rpm -ql python3-gobject-base
/usr/lib/.build-id
/usr/lib/.build-id/1e/0069b4c149b951f05d0a5cc7e422c776fb3e41
/usr/lib/.build-id/72
/usr/lib/.build-id/72/7fcbb7b6a5db436cd4485ae37a56cde151962c
/usr/lib64/python3.7/site-packages/PyGObject-3.34.0.egg-info
/usr/lib64/python3.7/site-packages/gi
/usr/lib64/python3.7/site-packages/gi/__init__.py
/usr/lib64/python3.7/site-packages/gi/__pycache__
/usr/lib64/python3.7/site-packages/gi/__pycache__/__init__.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/__init__.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_compat.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_compat.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_constants.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_constants.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_error.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_error.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_gtktemplate.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_gtktemplate.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_option.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_option.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_ossighelper.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_ossighelper.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_propertyhelper.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_propertyhelper.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_signalhelper.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/_signalhelper.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/docstring.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/docstring.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/importer.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/importer.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/module.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/module.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/pygtkcompat.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/pygtkcompat.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/types.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/__pycache__/types.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/_compat.py
/usr/lib64/python3.7/site-packages/gi/_constants.py
/usr/lib64/python3.7/site-packages/gi/_error.py
/usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so
/usr/lib64/python3.7/site-packages/gi/_gtktemplate.py
/usr/lib64/python3.7/site-packages/gi/_option.py
/usr/lib64/python3.7/site-packages/gi/_ossighelper.py
/usr/lib64/python3.7/site-packages/gi/_propertyhelper.py
/usr/lib64/python3.7/site-packages/gi/_signalhelper.py
/usr/lib64/python3.7/site-packages/gi/docstring.py
/usr/lib64/python3.7/site-packages/gi/importer.py
/usr/lib64/python3.7/site-packages/gi/module.py
/usr/lib64/python3.7/site-packages/gi/overrides
/usr/lib64/python3.7/site-packages/gi/overrides/GIMarshallingTests.py
/usr/lib64/python3.7/site-packages/gi/overrides/GLib.py
/usr/lib64/python3.7/site-packages/gi/overrides/GObject.py
/usr/lib64/python3.7/site-packages/gi/overrides/Gdk.py
/usr/lib64/python3.7/site-packages/gi/overrides/GdkPixbuf.py
/usr/lib64/python3.7/site-packages/gi/overrides/Gio.py
/usr/lib64/python3.7/site-packages/gi/overrides/Gtk.py
/usr/lib64/python3.7/site-packages/gi/overrides/Pango.py
/usr/lib64/python3.7/site-packages/gi/overrides/__init__.py
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/GIMarshallingTests.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/GIMarshallingTests.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/GLib.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/GLib.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/GObject.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/GObject.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/Gdk.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/Gdk.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/GdkPixbuf.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/GdkPixbuf.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/Gio.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/Gio.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/Gtk.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/Gtk.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/Pango.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/Pango.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/__init__.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/__init__.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/keysyms.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/__pycache__/keysyms.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/overrides/keysyms.py
/usr/lib64/python3.7/site-packages/gi/pygtkcompat.py
/usr/lib64/python3.7/site-packages/gi/repository
/usr/lib64/python3.7/site-packages/gi/repository/__init__.py
/usr/lib64/python3.7/site-packages/gi/repository/__pycache__
/usr/lib64/python3.7/site-packages/gi/repository/__pycache__/__init__.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/gi/repository/__pycache__/__init__.cpython-37.pyc
/usr/lib64/python3.7/site-packages/gi/types.py
/usr/lib64/python3.7/site-packages/pygtkcompat
/usr/lib64/python3.7/site-packages/pygtkcompat/__init__.py
/usr/lib64/python3.7/site-packages/pygtkcompat/__pycache__
/usr/lib64/python3.7/site-packages/pygtkcompat/__pycache__/__init__.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/pygtkcompat/__pycache__/__init__.cpython-37.pyc
/usr/lib64/python3.7/site-packages/pygtkcompat/__pycache__/generictreemodel.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/pygtkcompat/__pycache__/generictreemodel.cpython-37.pyc
/usr/lib64/python3.7/site-packages/pygtkcompat/__pycache__/pygtkcompat.cpython-37.opt-1.pyc
/usr/lib64/python3.7/site-packages/pygtkcompat/__pycache__/pygtkcompat.cpython-37.pyc
/usr/lib64/python3.7/site-packages/pygtkcompat/generictreemodel.py
/usr/lib64/python3.7/site-packages/pygtkcompat/pygtkcompat.py
/usr/share/doc/python3-gobject-base
/usr/share/doc/python3-gobject-base/NEWS
/usr/share/licenses/python3-gobject-base
/usr/share/licenses/python3-gobject-base/COPYING
```
