### ISSUE TITLE
cx_Freeze.freezer.ConfigError: cannot find pan-down-symbolic.symbolic.png

### ISSUE THREAD

**Issue by jeromerobert** [jeromerobert/pdfarranger#94]
Icon file names have changed since the last time I packaged pdfarranger for Windows.

```
$ /mingw64/bin/python3 setup_win32.py bdist_zip
running bdist_zip
Traceback (most recent call last):
  File "setup_win32.py", line 148, in <module>
    shortcutDir='StartMenuFolder'
  File "C:/msys2/mingw64/lib/python3.7/site-packages\cx_Freeze\dist.py", line 349, in setup
    distutils.core.setup(**attrs)
  File "C:/msys2/mingw64/lib/python3.7\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:/msys2/mingw64/lib/python3.7\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:/msys2/mingw64/lib/python3.7\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup_win32.py", line 131, in run
    build_exe.run()
  File "C:/msys2/mingw64/lib/python3.7/site-packages\cx_Freeze\dist.py", line 218, in run
    zipExcludePackages = self.zip_exclude_packages)
  File "C:/msys2/mingw64/lib/python3.7/site-packages\cx_Freeze\freezer.py", line 150, in __init__
    self._VerifyConfiguration()
  File "C:/msys2/mingw64/lib/python3.7/site-packages\cx_Freeze\freezer.py", line 470, in _VerifyConfiguration
    sourceFileName)
cx_Freeze.freezer.ConfigError: cannot find file/directory named C:/msys2/mingw64/share/icons/Adwaita/16x16/actions/pan-down-symbolic.symbolic.png

**Comment by jeromerobert** [comment]
* <https://gitlab.gnome.org/GNOME/adwaita-icon-theme/issues/15>
* <https://gitlab.gnome.org/GNOME/adwaita-icon-theme/issues/22>
